name: release
on: workflow_dispatch
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install Rust
        run: rustup toolchain install stable
      - name: Run doc tests
        run: cargo test --features 'backend-filesystem' --doc
      - name: Run tests
        run: cargo test --features 'backend-filesystem' --benches --examples --tests
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
  release:
    name: release
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish crate
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
