name: tests
on:
  push:
    branches:
      - "main"
    paths:
      - src/*
      - examples/*
      - benches/*
      - tests/*
      - .github/workflows/test.yml
  pull_request:
    branches:
      - "*"
    paths:
      - src/*
      - examples/*
      - benches/*
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run doc tests
        # llvm-cov has issues with doc tests, so we'll run those separately
        run: cargo test --features 'backend-filesystem' --doc
      - name: Test alternative flags
        # Testing some alternative flag configurations, like rustls and no logging
        run: cargo test --features 'backend-redis,backend-filesystem,backend-in-memory,backend-sqlite-rustls' --no-default-features --benches --examples --tests
      - name: Run tests
        run: cargo llvm-cov --features 'backend-filesystem' --benches --examples --tests --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
